[tool.poetry]
name = "remake"
version = "0.1.0"
description = ""
authors = ["drakes00 <drakes00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.4.2"
ward = "^0.67.2b0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
